stages:
- build
- test
- deploy

build:ubuntu-16.04:debug:
  image: haffmans/cmake-qt5:latest
  artifacts:
    paths:
    - build/ubuntu-16.04/debug
    expire_in: 30 days
  script:
  - mkdir -p build/ubuntu-16.04/debug
  - cd build/ubuntu-16.04/debug
  - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr ${CI_PROJECT_DIR}
  - make -j4
  stage: build

build:ubuntu-16.04:release:
  image: haffmans/cmake-qt5:latest
  artifacts:
    paths:
    - build/ubuntu-16.04/release
    expire_in: 30 days
  script:
  - mkdir -p build/ubuntu-16.04/release
  - cd build/ubuntu-16.04/release
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ${CI_PROJECT_DIR}
  - make -j4
  stage: build

build:win32:release:
  image: haffmans/mingw-qt5:latest
  artifacts:
    paths:
    - build/win32/release
    expire_in: 30 days
  script:
  - TOOLCHAIN=i686-w64-mingw32
  - ARCH=win32
  - DEPLOYTARGET="${CI_PROJECT_DIR}/images/${ARCH}/"

  - mkdir -p build/${ARCH}/release
  - cd build/${ARCH}/release
  - ${TOOLCHAIN}-cmake -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-${TOOLCHAIN}.cmake
    -DImageMagick_convert_EXECUTABLE=/usr/bin/convert
    -DCPACK_OUTPUT_FILE_PREFIX=${DEPLOYTARGET}
    -DCPACK_PACKAGE_VERSION=${CI_BUILD_REF_NAME}
    ${CI_PROJECT_DIR}
  - make -j4
  stage: build

build:win64:release:
  image: haffmans/mingw-qt5:latest
  artifacts:
    paths:
    - build/win64/release
    expire_in: 30 days
  script:
  - TOOLCHAIN=x86_64-w64-mingw32
  - ARCH=win64
  - DEPLOYTARGET="${CI_PROJECT_DIR}/images/${ARCH}/"

  - mkdir -p build/${ARCH}/release
  - cd build/${ARCH}/release
  - ${TOOLCHAIN}-cmake -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_TOOLCHAIN_FILE=/usr/share/mingw/toolchain-${TOOLCHAIN}.cmake
    -DImageMagick_convert_EXECUTABLE=/usr/bin/convert
    -DCPACK_OUTPUT_FILE_PREFIX=${DEPLOYTARGET}
    -DCPACK_PACKAGE_VERSION=${CI_BUILD_REF_NAME}
    ${CI_PROJECT_DIR}
  - make -j4
  stage: build

package:ubuntu-16.04:
  image: haffmans/cmake-qt5:latest
  artifacts:
    paths:
    - images
    expire_in: 30 days
  dependencies:
  - build:ubuntu-16.04:release
  script:
  # Defaults
  - TARGET="${CI_PROJECT_DIR}/images/linux/"
  - PACKNAME="GraphicsRulesMaker-${CI_BUILD_REF_NAME}"

  # Determine distribution name + release
  - if [ -f /etc/lsb-release ]; then
  -   '. /etc/lsb-release'
  -   DISTRIB_ID_LC=$(echo "$DISTRIB_ID" | tr "[:upper:]" "[:lower:]")
  -   TARGET="${CI_PROJECT_DIR}/images/${DISTRIB_ID_LC}/${DISTRIB_CODENAME}/"
  - fi

  # Install to temporary directory
  - cd build/ubuntu-16.04/release
  - mkdir -p "${CI_PROJECT_DIR}/package/ubuntu-16.04/${PACKNAME}"
  - make DESTDIR="${CI_PROJECT_DIR}/package/ubuntu-16.04/${PACKNAME}" install

  # Prepare target
  - cd "${CI_PROJECT_DIR}/package/ubuntu-16.04/${PACKNAME}"
  - mkdir -p "$TARGET"

  # Create tar.gz and tar.bz2
  - echo "Creating ${TARGET}${PACKNAME}.tar.gz..."
  - tar -czpf "${TARGET}${PACKNAME}.tar.gz" *
  - echo "Creating ${TARGET}${PACKNAME}.tar.bz2..."
  - tar -cjpf "${TARGET}${PACKNAME}.tar.bz2" *

  # Creating checksums
  - cd "${TARGET}"
  - md5sum "${PACKNAME}.tar.gz" > "${PACKNAME}.tar.gz.md5"
  - sha1sum "${PACKNAME}.tar.gz" > "${PACKNAME}.tar.gz.sha1"
  - md5sum "${PACKNAME}.tar.bz2" > "${PACKNAME}.tar.bz2.md5"
  - sha1sum "${PACKNAME}.tar.bz2" > "${PACKNAME}.tar.bz2.sha1"
  stage: deploy

package:src:
  image: haffmans/cmake-qt5:latest
  artifacts:
    paths:
    - images
    expire_in: 30 days
  script:
  - TARGET="${CI_PROJECT_DIR}/images/src/"
  - PACKNAME="GraphicsRulesMaker-${CI_BUILD_REF_NAME}"
  - mkdir -p "$TARGET"

  - echo "Creating ${TARGET}${PACKNAME}.src.tar.gz..."
  - git archive --prefix=${PACKNAME}/ ${CI_COMMIT_SHA} | gzip > "${TARGET}${PACKNAME}.src.tar.gz"

  - echo "Creating ${TARGET}${PACKNAME}.src.tar.bz2..."
  - git archive --prefix=${PACKNAME}/ ${CI_COMMIT_SHA} | bzip2 > "${TARGET}${PACKNAME}.src.tar.bz2"

  # Creating checksums
  - cd "${TARGET}"
  - md5sum "${PACKNAME}.src.tar.gz" > "${PACKNAME}.src.tar.gz.md5"
  - sha1sum "${PACKNAME}.src.tar.gz" > "${PACKNAME}.src.tar.gz.sha1"
  - md5sum "${PACKNAME}.src.tar.bz2" > "${PACKNAME}.src.tar.bz2.md5"
  - sha1sum "${PACKNAME}.src.tar.bz2" > "${PACKNAME}.src.tar.bz2.sha1"
  stage: deploy

package:win32:
  image: haffmans/mingw-qt5:latest
  artifacts:
    paths:
    - images
    expire_in: 30 days
  dependencies:
  - build:win32:release
  script:
  - TOOLCHAIN=i686-w64-mingw32
  - ARCH=win32
  - DEPLOYTARGET="${CI_PROJECT_DIR}/images/${ARCH}/"
  - PACKNAME=GraphicsRulesMaker-${CI_BUILD_REF_NAME}-${ARCH}

  - cd build/${ARCH}/release
  - cpack -DCPACK_OUTPUT_FILE_PREFIX=${DEPLOYTARGET} -DCPACK_PACKAGE_VERSION=${CI_BUILD_REF_NAME}

  # Creating checksums
  - cd "${DEPLOYTARGET}"
  - md5sum "${PACKNAME}.exe" > "${PACKNAME}.exe.md5"
  - sha1sum "${PACKNAME}.exe" > "${PACKNAME}.exe.sha1"
  - md5sum "${PACKNAME}.zip" > "${PACKNAME}.zip.md5"
  - sha1sum "${PACKNAME}.zip" > "${PACKNAME}.zip.sha1"
  stage: deploy

package:win64:
  image: haffmans/mingw-qt5:latest
  artifacts:
    paths:
    - images
    expire_in: 30 days
  dependencies:
  - build:win64:release
  script:
  - TOOLCHAIN=x86_64-w64-mingw32
  - ARCH=win64
  - DEPLOYTARGET="${CI_PROJECT_DIR}/images/${ARCH}/"
  - PACKNAME=GraphicsRulesMaker-${CI_BUILD_REF_NAME}-${ARCH}

  - cd build/${ARCH}/release
  - cpack -DCPACK_OUTPUT_FILE_PREFIX=${DEPLOYTARGET} -DCPACK_PACKAGE_VERSION=${CI_BUILD_REF_NAME}

  # Creating checksums
  - cd "${DEPLOYTARGET}"
  - md5sum "${PACKNAME}.exe" > "${PACKNAME}.exe.md5"
  - sha1sum "${PACKNAME}.exe" > "${PACKNAME}.exe.sha1"
  - md5sum "${PACKNAME}.zip" > "${PACKNAME}.zip.md5"
  - sha1sum "${PACKNAME}.zip" > "${PACKNAME}.zip.sha1"
  stage: deploy

